### ISSUE TITLE
Difficulty settings

### ISSUE THREAD

**Issue by KingHeavy** [Task-Force-Red/Operation-Red-Meteor#13]
need to know which ones the right ones are, or have them corrected to be right.

**Comment by Jmaster9999** [comment]
Are you asking about the difficulty preset? Ai difficulty? Ace difficulty? If you're refering to the difficulty preset (Forced first-person,etc), you don't need to worry about setting setting it in the mission file. The server profile we use has that all setup. Those mission-side settings get overridden anyways. 

AI difficulty is up to you, although usually anything above 0.95? turns the ai into unstoppable aim-bots. Ace module settings are kinda up to you right now, although I'd like to have them standardized so I can create a guide and criteria for mission makers setting up ace. (Use ace advanced medical, use ace ballistics, set this bleed-out threshold, etc)
