### ISSUE TITLE
Configuring Boxes

### ISSUE THREAD

**Issue by KingHeavy** [Task-Force-Red/Operation-Red-Meteor#15]
I added box configs in the update i pushed for the mod today, they don't seem to be working.
obviously i cannot box. please help. this is pretty much just an effort to save the base from being super cluttered.

**Comment by Jmaster9999** [comment]
I'll see what I can do when I get home/am free. Are the boxes just not showing up in editor? Is the mod erroring? Or are the boxes spawning empty/incomplete

**Comment by KingHeavy** [comment]
Done! some minor issues in the code not withstanding. just ignore them and push on. i'm done for the night on this.
