### ISSUE TITLE
TFAR bug

### ISSUE THREAD

**Issue by coachwn** [Task-Force-Red/Operation-Red-Meteor#3]
Several players getting bugged out with TFAR on joining the server. Very frustrating since it works on the full time mission.

**Comment by KingHeavy** [comment]
Likely the tfar module incorrectly setup. will attempt to correct on next github update.

**Comment by KingHeavy** [comment]
possibly fixed, need to test and see if it works for sure.

**Comment by KingHeavy** [comment]
It works. tested with myself, no issues getting pulled or into the channel whatsoever. Seeing as literally just me and tate were having issues, I'm calling it good.
