### ISSUE TITLE
Ambient radio sounds are extremely low

### ISSUE THREAD

**Issue by coachwn** [Task-Force-Red/Operation-Red-Meteor#4]
Possible TFAR bug with volume sounds super low. Need to check and see what the issues are with this as it might be a TFAR bug or an issue with the sounds in general.

**Comment by KingHeavy** [comment]
to provide a temporary band-aid, I gave pilots a box with backpack radios.

**Comment by coachwn** [comment]
Backpack radios work much better for the crew now.
