### ISSUE TITLE
pilot earplugs

### ISSUE THREAD

**Issue by KingHeavy** [Task-Force-Red/Operation-Red-Meteor#6]
hurp derp, i goofed.

**Comment by KingHeavy** [comment]
given in a box.

**Comment by Jmaster9999** [comment]
Could we get these in the load-outs?

**Comment by KingHeavy** [comment]
I would, but i need to test and see which radio you guys want to have first. i put both the infantry radios that our infantry guys use, and the regular rhs MR-6000L's, but the 6000L's textures are absolutely fucked up. Also, i'm not sure what the range is on the radios the infantry use, i think Nichols tested that out, so he'd probably be able to give a range estimation.
