### ISSUE TITLE
Helicopter Fuel Usage

### ISSUE THREAD

**Issue by KingHeavy** [Task-Force-Red/Operation-Red-Meteor#8]
not sure where to go with this, it's default RHS.

**Comment by Jmaster9999** [comment]
What's the problem with RHS fuel usage? I haven't noticed any issues...

**Comment by Jmaster9999** [comment]
This can be fixed, you need to write a config to override the RHS helicopter fuel consumption and fuel capacity values.

**Comment by coachwn** [comment]
To much code work around needed...pilots will just have to deal with it and plan accordingly.
